### ISSUE TITLE
Bleuclair theme overlapping on "Associated revisions"

### ISSUE THREAD

**Issue by tevino** [redmica/redmica#110]
The vertical history line at the left is overlapping with the content on "Associated revisions"

**Associated revisions**
<img width="658" alt="Screenshot 2023-12-05 at 11 45 31" src="https://github.com/redmica/redmica/assets/1027300/eb2bbbf2-e92d-4e6f-b104-7736c39cb488">

**Notes**
<img width="581" alt="Screenshot 2023-12-05 at 11 39 35" src="https://github.com/redmica/redmica/assets/1027300/d2339cf9-cb7a-4198-9ed9-21a9b146681c">

Redmica: 2.3.2.stable

CC @ishikawa999

**Comment by ishikawa999** [comment]
@tevino 
Thank you for your report. Considering your feedback, I have made corrections at https://github.com/farend/redmine_theme_farend_bleuclair/pull/77. After observing the situation for a while, I plan to create a pull request with these changes for RedMica.

**Comment by tevino** [comment]
@ishikawa999 Thanks for the prompt adjustment, I just tried with the `master` branch of https://github.com/farend/redmine_theme_farend_bleuclair and it turned out great, thank you!

Also, I didn't find any description of the integration of Redmica and the theme, could you brief me about the relationship of this folder https://github.com/redmica/redmica/tree/master/public/themes/bleuclair and the original repository of the theme?

**Comment by ishikawa999** [comment]
Thank you for confirming the operation. I'm relieved to hear that the issue has been resolved.

> Also, I didn't find any description of the integration of Redmica and the theme, could you brief me about the relationship of this folder https://github.com/redmica/redmica/tree/master/public/themes/bleuclair and the original repository of the theme?

I apologize for the lack of sufficient documentation. When there are significant changes or necessary fixes in the original repository of the bleuclair theme, I apply these changes to RedMica as well. During these changes, I create issues and pull requests similar to [#108](https://github.com/redmica/redmica/issues/108) and [#109](https://github.com/redmica/redmica/pull/109).
I will create an issue and pull request to apply the current Bleuclair theme once I have verified if there are any other changes that need to be made.

**Comment by tevino** [comment]
In that case I'm considering this issue as solved.

Appreciation to @ishikawa999

**Comment by ishikawa999** [comment]
@tevino 
Thanks!

**Comment by ishikawa999** [comment]
@tevino 
The reported fixes have also been merged into RedMica. c6fb2d7f75675e8799ab618fe2fdd8e1bc3c3b95
If you use the code from the latest stable-2.4 branch, you can use RedMica with the problem fixed.
Thank you for your report.

**Comment by tevino** [comment]
@ishikawa999 

Thanks for the tip, and congrats on the merge.
I just tried [the latest Docker image][latest], the bug is still there, I then realize that the latest is 2.4.1 which was built before the merge.
Will it be included in the image of 2.4.2?

[latest]: https://hub.docker.com/layers/redmica/redmica/2.4.1/images/sha256-2576f29db8559607bad37fdb422f1fde860aa7e04f0c092152f9471588dbd4e9?context=explore
